name: Kingdom of Elaria I

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build Kingdom of Elaria I
        run: npm run dist

      - name: Upload Kingdom of Elaria I
        uses: actions/upload-artifact@v4
        with:
          name: Kingdom of Elaria I
          path: release/*.exe
          if-no-files-found: error
